server:
  port: 8085
  servlet:
    context-path: /chat
spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/chat-service?authSource=admin
      auto-index-creation: true

services:
  profile:
    url: http://localhost:9002/profile